### ISSUE TITLE
Do we need copyright headers in files?

### ISSUE THREAD

**Issue by drasko** [drasko/edgex-export#11]
There is on-going discussion on EdgeX mainlinig lists should we keep or drop copyright headers.

**Comment by ojongerius** [comment]
Kate Stewart gave a well voiced motivation in the EdgeX mailing list that pleads for doing so:

> A single line comment with "SPDX-License-Identifier: Apache-2.0"
is not generally perceived as too painful a bloat by most developers,
and lets the automated tooling find it to summarize accurately.

> The DCO [1] wording expects the developer to "submit it under the 
open source license indicated in the file".   U-Boot started using SPDX
identifiers in its files several years ago, and other projects (like mbed,
Zephyr, etc.) have been adopting this convention to ensure each file 
has a unambiguously detectable license reference in the file.

> Part of what will make Edge-X successful will be companies feeling
confident using it.  Unambiguous licensing, kept up to date by automatic
tooling, definitely helps with the companies have confidence the code
doesn't have "surprises" in it.   Adding at a minimum a one-line SPDX 
license statement per file that tooling can detect and summarize easily 
removes a lot of "assumptions", and really helps in the goal.

**Comment by drasko** [comment]
After a discussion on ML and TSC, it was decided that copyright headers be mandatory for now. I opted for SPDX-style headers, and this is what is currently added to the code base.
