### ISSUE TITLE
logger in Go implementation of export service.

### ISSUE THREAD

**Issue by jay11ca39** [drasko/edgex-export#12]
Hello all,

I have one query regarding "**Go implementation for export services"**.
For logger:
1. Will write a edgex-logger as we have in our java implementation [**support-logging-client service**] ?
2. Will use as-is already existing logger libraries in GO ? 
    For example: https://github.com/sirupsen/logrus
                         https://github.com/golang/glog

Thanks in advance.

**Comment by drasko** [comment]
We already started implementation with Uber Zap: https://github.com/drasko/edgex-export/blob/master/cmd/client/main.go#L53

`logrus` looked very good ans is very popular, but on the README we can see that sirupsen is looking for maintainer, as he has no time to maintain it anymore: https://github.com/sirupsen/logrus

Uber Zap looks like very active project: https://github.com/uber-go/zap, from a respective company. So we opted for this solution internally.

I will propose this as a choice to TSC, but of course everybody can propose alternatives.
