### ISSUE TITLE
Consider moving this to the EdgeX Foundry project

### ISSUE THREAD

**Issue by ojongerius** [drasko/edgex-export#17]
It will increase visibility, and should end up there in the long run anyway?

**Comment by drasko** [comment]
Sure, and this is what I proposed already. It's been discussed on ML, and majority opted that we fix minimum before.

I think it is ready now, but waiting green light (and permissions :)) from EdgeX maintainers. Someone has to create repos over there.

**Comment by ojongerius** [comment]
Great to hear.
