### ISSUE TITLE
Create Registration Notification Mechanism for `client`

### ISSUE THREAD

**Issue by drasko** [drasko/edgex-export#34]
Registration notifications bus should be implemented in `client`. Distribution service should keep an internal cache of registration data and use this notification bus to update it's cache and keep it coherent.

**Comment by drasko** [comment]
@feclare took care of this: https://github.com/drasko/edgex-export/pull/41

@feclare I just saw that you used `GET` so post notifications. Can you please change this and preferably use `POST` or `PUT` - it would be more logical.

**Comment by feclare** [comment]
As it had no data I thought a GET was the right one, but I don't mind changing it. Which one do you prefer? POST or PUT?

**Comment by drasko** [comment]
@mijicd ^

**Comment by mijicd** [comment]
If it should be idempotent, use `PUT`. Otherwise use `POST`.

**Comment by drasko** [comment]
@feclare wait... you are sending notifications, and have no data? i thought you are sending new registration content that came to `client` via client's REST API towards `distro`... What are you sending to `distro` then, if not new (updated) registration info?

**Comment by feclare** [comment]
@drasko  It is just a notification that _something_ has changed with the registrations. Distro reads all the registrations and update them as needed.

@mijicd `PUT` then. Thanks

**Comment by drasko** [comment]
@feclare this is not a good design I think - this is not what we discussed. Distro should ask `client` for registrations only on boot. After this, `distro` should maintain it's own cache, and updates should be sent via notifications - i.e. new content should be sent to `distro` via this HTTP PUT. Distro should never again ask the `client` to give it "all the registrations" - because it will be in sync via these notifications which send all new content.

**Comment by feclare** [comment]
@drasko I completely disagree with that. If we are going to add all the client api as notifications (add, update, remove) we are duplicating almost all the client api, without the getters. 

I don't know why you think there is a problem related to the reloading of all the registration data. 
The registrations will not change often, reloading all of them when there is a change is easy and does not have too much overhead. We can even fine-tune the update algorithm not to recreate the mqtt connections, that is the only problem of the current implementation. 

There is no need to over complicate the notifications api.

**Comment by drasko** [comment]
@feclare I see... I understand the problem. Let's consult with @mijicd, @janko-isidorovic and @nmarcetic and also I think it would be important to get the opinion from Jim and other experts on ML.

This is in my opinion probably the biggest problem we have to solve in Export Services, apart from ZMQ. Everything else should be more or less straightforward (I hope, at least :)). So let's see together how to solve this well.

**Comment by nmarcetic** [comment]
Hi @feclare I agree with @drasko. Please don't get me wrong, but Its a bad practice and design. I understand your thoughts and the way your are thinking, maybe your are right about  `registrations will not change often` but we don't know that :) Do you agree ? 
This is really bother me `reloading of all the registration data.`  You don't know how often changes will happen and how this can affect the system in production.
I would suggest you to think about it, hope you will change your thoughts :)

You don't need to copy whole client code, basically you only need one API end point, just change the message type (e.g if is add you send type: 'add' if is create you send type: 'create' etc...) parsing of this message is simple then just go over switch case or map and update your local cache. It can be done in a few lines of code I think. 
Thanks.

**Comment by drasko** [comment]
@nmarcetic @feclare yes - one endpoint and then demultiplex with `switch` - it should be just a few lines of code. And it will look much better architecture-wise.

**Comment by feclare** [comment]
@nmarcetic @drasko Thanks for the comments and the discussion. 

I understand your comments and will implement your design. It is clear that it is more complete and elegant design than mine. I was just trying to keep it as simple as possible.

**Comment by drasko** [comment]
@feclare can this one be closed now?

**Comment by feclare** [comment]
Yes, it can be closed.

I think we did a good job, thanks @drasko @mijicd @nmarcetic
